### ISSUE TITLE
[Enhancement] Ability to save files locally with file extension and folder structure.

### ISSUE THREAD

**Issue by rayep** [adityatelange/bhhb#17]
Hi @adityatelange,

Thank you for creating 'bhhb' extension, it's really helpful. :)

Would it be possible to add a feature that can export the files to local file system with their native formats and retaining folder structures? i.e., if a file content URL looks like https://www.example.com/static/assets/images/image1.png then the content should be stored as,

**Folder path:** Inside www.example.com >> static >> assets >> images folder
**File name:** image1.png

Similar to "Save All Resources" browser extension - https://chrome.google.com/webstore/detail/save-all-resources/abpdnfjocnmdomablahdcfnoggeeiedb?hl=en

Thank you!

**Comment by rayep** [comment]
Filed under ER section.

**Comment by rayep** [comment]
Sorry, was not sure how to add 'enhancement' label, hence reopened the issue.

**Comment by rayep** [comment]
@adityatelange Any thoughts?

**Comment by adityatelange** [comment]
> @adityatelange Any thoughts?

Parsing requests and making a folder structure seems to be too much work for me. I don't find a good reason to export the files when all I want to do is analyse the request and response.
